gui:
  nerdFontsVersion: "3"
  showBottomLine: false
os:
  editPreset: 'nvim'
notARepository: 'skip'
keybinding:
  global:
    undo: '<c-z>'
    redo: '<c-y>'
  commits:
    renameCommit: 'r'
    viewResetOptions: '<delete>'
confirmOnQuit: true
