gui:
  theme:
    activeBorderColor:
      - '#ea76cb'
      - bold
    inactiveBorderColor:
      - '#6c6f85'
    optionsTextColor:
      - '#1e66f5'
    selectedLineBgColor:
      - '#ccd0da'
    cherryPickedCommitBgColor:
      - '#bcc0cc'
    cherryPickedCommitFgColor:
      - '#ea76cb'
    unstagedChangesColor:
      - '#d20f39'
    defaultFgColor:
      - '#4c4f69'
    searchingActiveBorderColor:
      - '#df8e1d'

  authorColors:
    '*': '#7287fd'
  nerdFontsVersion: "3"
  showBottomLine: false
os:
  editPreset: 'nvim'
notARepository: 'skip'
keybinding:
  global:
    undo: '<c-z>'
    redo: '<c-y>'
  commits:
    renameCommit: 'r'
    viewResetOptions: '<delete>'
confirmOnQuit: true
